
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPServerInterface", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPServerInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AirbusList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AirbusList", targetNamespace = "http://ws/", className = "client.AirbusList")
    @ResponseWrapper(localName = "AirbusListResponse", targetNamespace = "http://ws/", className = "client.AirbusListResponse")
    @Action(input = "http://ws/SOAPServerInterface/AirbusListRequest", output = "http://ws/SOAPServerInterface/AirbusListResponse")
    public String airbusList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BoeingList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BoeingList", targetNamespace = "http://ws/", className = "client.BoeingList")
    @ResponseWrapper(localName = "BoeingListResponse", targetNamespace = "http://ws/", className = "client.BoeingListResponse")
    @Action(input = "http://ws/SOAPServerInterface/BoeingListRequest", output = "http://ws/SOAPServerInterface/BoeingListResponse")
    public String boeingList();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removefromcart", targetNamespace = "http://ws/", className = "client.Removefromcart")
    @ResponseWrapper(localName = "removefromcartResponse", targetNamespace = "http://ws/", className = "client.RemovefromcartResponse")
    @Action(input = "http://ws/SOAPServerInterface/removefromcartRequest", output = "http://ws/SOAPServerInterface/removefromcartResponse")
    public String removefromcart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewcart", targetNamespace = "http://ws/", className = "client.Viewcart")
    @ResponseWrapper(localName = "viewcartResponse", targetNamespace = "http://ws/", className = "client.ViewcartResponse")
    @Action(input = "http://ws/SOAPServerInterface/viewcartRequest", output = "http://ws/SOAPServerInterface/viewcartResponse")
    public String viewcart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyitems", targetNamespace = "http://ws/", className = "client.Buyitems")
    @ResponseWrapper(localName = "buyitemsResponse", targetNamespace = "http://ws/", className = "client.BuyitemsResponse")
    @Action(input = "http://ws/SOAPServerInterface/buyitemsRequest", output = "http://ws/SOAPServerInterface/buyitemsResponse")
    public String buyitems(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "additemtocart", targetNamespace = "http://ws/", className = "client.Additemtocart")
    @ResponseWrapper(localName = "additemtocartResponse", targetNamespace = "http://ws/", className = "client.AdditemtocartResponse")
    @Action(input = "http://ws/SOAPServerInterface/additemtocartRequest", output = "http://ws/SOAPServerInterface/additemtocartResponse")
    public String additemtocart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EmbraerList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EmbraerList", targetNamespace = "http://ws/", className = "client.EmbraerList")
    @ResponseWrapper(localName = "EmbraerListResponse", targetNamespace = "http://ws/", className = "client.EmbraerListResponse")
    @Action(input = "http://ws/SOAPServerInterface/EmbraerListRequest", output = "http://ws/SOAPServerInterface/EmbraerListResponse")
    public String embraerList();

}
